app = "cms-web-gki-pregbun"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  SESSION_DRIVER = "cookie"
  CACHE_STORE = "array"
  QUEUE_CONNECTION = "sync"
  FILESYSTEM_DISK = "cloudinary"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
